language: php

sudo: false

addons:
  postgresql: "9.3"

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.6
 - 7.0
 - 7.1

env:
  matrix:
    - DB=pgsql MOODLE_BRANCH=MOODLE_27_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_27_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_28_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_28_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_29_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_29_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_30_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_30_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install node
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  #- moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  #- moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
